---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[my-server::default]
      - recipe[my-server::tmux]
    attributes:
